 const GET_COUNTRIES= "GET_COUNTRIES"
 const GET_COUNTRY="GET_COUNTRY"
const GET_CONTINENTS="GET_CONTINENTS"
const GET_ACT_COUNTRY="GET_ACT_COUNTRY"
const GET_ORDER_A_Z="GET_ORDER_A_Z"
const GET_ORDER_Z_A="GET_ORDER_Z_A"
const POPULATION_A="POPULATION_A"
const POPULATION_D="POPULATION_D"
const RESET ="RESET"
const RESETC="RESETC"
 module.exports={
    GET_COUNTRIES,
    GET_COUNTRY,
    GET_CONTINENTS,
    GET_ACT_COUNTRY,
    GET_ORDER_A_Z,
    GET_ORDER_Z_A,
    POPULATION_A,
    POPULATION_D,
    RESET,
    RESETC
 }
