# fly.toml app configuration file generated for countriesdbpi on 2023-07-28T15:46:11-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "countriesdbpi"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  FRONTEND_ORIGIN_URL="https://proyecto-individual-six.vercel.app/"